# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rush01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'Alamofire'
  pod 'SwiftyJSON'

end
