# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day07' do
  use_frameworks!
  
  pod 'RecastAI'
  pod 'DarkSkyKit'
  pod 'JSQMessagesViewController'

end
