print("all cards:")
print(Deck.allCards)
print("\nall spades")
print(Deck.allSpades)
print("\nall diamonds")
print(Deck.allDiamonds)
print("\nall hearts")
print(Deck.allHearts)
print("\nall clubs")
print(Deck.allClubs)
